export const Errors = {
  INVALID_CATALOG_CONFIGURATION: 'INVALID_CATALOG_CONFIGURATION',
  KIT_NOT_FOUND: 'KIT_NOT_FOUND',
  INVALID_CREATE_PROJECT_INPUT: 'INVALID_CREATE_PROJECT_INPUT',
  TARGET_DIR_EXISTS: 'TARGET_DIR_EXISTS',
}
